### ISSUE TITLE
Setting IDs on elements

### ISSUE THREAD

**Issue by mattparlane** [voloko/uki#1]
Firstly, I really like Uki, it's an interesting idea.

I have been experimenting with using Uki and jQuery on the same page, and I've found it's a bit tricky.  The diff below adds a line that sets the id directly on the element, which means you can do things like this:

$("#myButton").click(function() { ...

instead of having to use the uki("#myButton") method.

I haven't come across any issues with doing this...  any thoughts?

Cheers,

Matt Parlane

<pre>
diff --git a/src/uki-core/view/base.js b/src/uki-core/view/base.js
index 66af695..dc6076e 100644
--- a/src/uki-core/view/base.js
+++ b/src/uki-core/view/base.js
@@ -108,6 +108,7 @@ uki.view.Base = uki.newClass(uki.view.Observable, new function() {
         if (id === undefined) return this._id;
         if (this._id) uki.unregisterId(this);
         this._id = id;
+        this._dom.id = id;
         uki.registerId(this);
         return this;
     };
</pre>

**Comment by voloko** [comment]
In case of a Button there's no difference. Using uki('#button').click(...) sets a handler on the top element of the button view. uki('#id') lookup is a bit faster then $('#id') lookup. And you can't uki('').unbind if you use jQuery call.

In case of a TextField there's a difference. When you set keypress on a TextField uki will bind it to <input> not to the container node.

Nevertheless I'm now setting id on a dom node.
http://github.com/voloko/uki/commit/af9f0a035b06383becb8b0e4eef0edda33362d68

**Comment by mattparlane** [comment]
Sweet, that sounds like it solves my problem.  Cheers.
