### ISSUE TITLE
Slider only allows a min value of 0

### ISSUE THREAD

**Issue by jacobstanley** [voloko/uki#18]
I'm using uki 0.3.4 and I'm trying to create a slider that goes from -5 to 20 by doing this:

```
uki({
    view: 'Slider',
    rect: '10 20 100 0',
    min: '-5',
    max: '20',
    value: '0'
}).attachTo(window);
```

But my min value of -5 seems to be getting ignored and the slider behaviour isn't quite right.

Thanks!

**Comment by voloko** [comment]
fixed with 0.3.5.
