### ISSUE TITLE
Doesn't work in IE6

### ISSUE THREAD

**Issue by boxabirds** [voloko/uki#2]
Very impressive! But sadly the Wave demo shows nothing at all in IE6, and the other demos are visually messed up too. 

Do you have any thoughts on when you might add IE6 support?

**Comment by voloko** [comment]
http://ukijs.org/functional/wave.html should work on IE6. At least it works now in my IE6 SP3. IE6 is supported, though with transparency removed.

**Comment by boxabirds** [comment]
Strange. There was definitely something wrong with the pages when I tried before, but now all the demos work awesomely.

**Comment by boxabirds** [comment]
PS this is IE6.0.2900.2180 / xpsp2 that the demos now work under. Only small thing is the fonts are a slightly different size in IE6 (rectifiable through a simple reset style css I'm sure and unrelated to layout) and as you say, no transparency which I'm seeing in the wave demo as no drop-shadow.

This is seriously amazing work Voloko.

**Comment by voloko** [comment]
Glad it worked. 
Thank you.
