### ISSUE TITLE
Object Expected Error!

### ISSUE THREAD

**Issue by chibuzoo** [voloko/uki#28]
Thanks for such a great looking framework.

I have spent the past two days trying to get the buttons example to work.

I keep getting 'Object Expected' Error from button.js line 1.

Please help!!  I'm losing hair fast becaus eo fthis.

Thanks,

**Comment by voloko** [comment]
Are you using 0.3.\* or the 0.4.0 alpha builds?

**Comment by chibuzoo** [comment]
Hi,

I'm using 0.3.8.

**Comment by chibuzoo** [comment]
Hi,

How can I get 0.4.0?

Is that what I should be using?
