### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by vjousse** [voloko/uki#29]
Hi,

Examples on the website are not available through the Git repo ...

http://ukijs.org/examples/core-examples/splitPane/splitPane.js

is not the same than https://github.com/voloko/uki/blob/master/examples/core-examples/splitPane/splitPane.js

Which one is the correct one?

**Comment by voloko** [comment]
Fixed that. Now they point to the last 0.3 build

**Comment by vjousse** [comment]
Thanks a lot!
