### ISSUE TITLE
Readme install docs do not work

### ISSUE THREAD

**Issue by drudru** [voloko/uki#35]
i installed node and npm

i did npm install ukijs
there is no express.js in my directory.

$ find . -name express.js
./node_modules/ukijs/express.js
./node_modules/ukijs/node_modules/express/lib/express.js

is this because npm is now 1.0.6 ?

**Comment by voloko** [comment]
You need to git clone the project to your hard drive. You'll see
express.js in the root folder

On 5/22/11 4:50 PM, "drudru"
reply@reply.github.com
wrote:
