### ISSUE TITLE
ImageCutter in Chrome 4.0.303 Window Resize Issue

### ISSUE THREAD

**Issue by prime31** [voloko/uki#4]
First off, incredible work!  Uki is coming along great and I look forward to seeing where it goes in the future.

I realize the ImageCutter (http://ukijs.org/imageCutter/prod.html) doesn't work in any other browser than Firefox but the layout system doesn't seem to work in Chrome.  Resizing the window causes the layout to end up being smaller than the window size.

**Comment by voloko** [comment]
http://github.com/voloko/uki/commit/b81d1454d1d8aeb19d64eb09c03ba1a50f6f4cc1
This one fixes the issue. Releasing 0.0.8a. It looks like chrome has some issues with js optimization. Do you know how to post a bug to chrome?
