### ISSUE TITLE
uki for modern browsers

### ISSUE THREAD

**Issue by cloudhead** [voloko/uki#8]
Is there any way to strip out all the IE6/7 compatibility code, to make uki lighter? I'm not interested in supporting those browsers, but uki looks really interesting.

**Comment by voloko** [comment]
There's not much compatibility code for IE6/7 browsers. The only noticeable thing is fallback image urls. But they a) can be easily removed from the theme file b) do not really consume much space (less then 3%).

All the other things like d&d fallback, layout fallback are used by opera, ff3, and even some version of Chrome. So there's not much I can cut off without hurting them.

**Comment by cloudhead** [comment]
Alright, good to know! I thought maybe uki was using canvas on modern browsers, and svg on older ones.
